update_fastlane

default_platform(:ios)

platform :ios do
  desc  "Generates a build of HSAttachmentPicker.xcframework"
  lane :build_framework do
    sh("cd ..; sh Scripts/build_framework.sh")
  # Create an XCFramework of the device and simulator frameworks
  sh("cd ..; sh Scripts/create_xcframework.sh")
  end
end
